name: sahatkom
description: "Application de prise de rendez-vous médicaux"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  
  # Icons
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/hero_image.png
    - assets/images/doctor_avatar.png
    - assets/images/doctors/